/**
 *  Types for PokemonList
 * */
export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST'
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const GET_POKEMONS_FAIL = 'GET_POKEMONS_FAIL'

export const GET_SIMILAR_POKEMONS_REQUEST = 'GET_SIMILAR_POKEMONS_REQUEST'
export const GET_SIMILAR_POKEMONS_SUCCESS = 'GET_SIMILAR_POKEMONS_SUCCESS'
export const GET_SIMILAR_POKEMONS_FAIL = 'GET_SIMILAR_POKEMONS_FAIL'

export const GET_SINGLE_POKEMON_REQUEST = 'GET_SINGLE_POKEMON_REQUEST'
export const GET_SINGLE_POKEMON_SUCCESS = 'GET_SINGLE_POKEMON_SUCCESS'
export const GET_SINGLE_POKEMON_FAIL = 'GET_SINGLE_POKEMON_FAIL'
export const CLEAR_SINGLE_POKEMON_ERROR = 'CLEAR_SINGLE_POKEMON_ERROR'