/**
 *  Types for PokemonList
 * */
export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST'
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const GET_POKEMONS_FAIL = 'GET_POKEMONS_FAIL'
export const GET_SIMILAR_POKEMONS_REQUEST = 'GET_SIMILAR_POKEMONS_REQUEST'
export const GET_SIMILAR_POKEMONS_SUCCESS = 'GET_SIMILAR_POKEMONS_SUCCESS'
export const GET_SIMILAR_POKEMONS_FAIL = 'GET_SIMILAR_POKEMONS_FAIL'